name: Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature**'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: actions-runner
      REGISTRY: ${{ secrets.registry }}
      BUILD_CACHE: /home/runner/.docker/buildkit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: "${{ secrets.REGISTRY }}"
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Prepare image tag
        id: prep
        run: |
          SHA=$(echo ${GITHUB_SHA} | head -c8)
          BUILDNUM=${{ github.run_number }}
          IMAGE=${REGISTRY}/${APP_NAME}
          (echo "tagged_image=${IMAGE}:${BUILDNUM}-${SHA},${IMAGE}:latest") >> "$GITHUB_OUTPUT"
          (echo "build_cache=${IMAGE}:buildcache") >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.prep.outputs.tagged_image }}
          cache-from: type=registry,ref=${{ steps.prep.outputs.build_cache }}
          cache-to: type=inline
